2022-08-09 06:40:21 - loading data from datasets/youtube/train.json
  0%|          | 0/1586 [00:00<?, ?it/s]100%|██████████| 1586/1586 [00:00<00:00, 2164714.01it/s]
2022-08-09 06:40:21 - loading data from datasets/youtube/valid.json
  0%|          | 0/120 [00:00<?, ?it/s]100%|██████████| 120/120 [00:00<00:00, 1421797.97it/s]
2022-08-09 06:40:21 - loading data from datasets/youtube/test.json
  0%|          | 0/250 [00:00<?, ?it/s]100%|██████████| 250/250 [00:00<00:00, 1702233.77it/s]
2022-08-09 06:40:21 - loading features from datasets/youtube/train_bert.pkl
2022-08-09 06:40:21 - loading features from datasets/youtube/valid_bert.pkl
2022-08-09 06:40:21 - loading features from datasets/youtube/test_bert.pkl
Traceback (most recent call last):
  File "fwrench/applications/pipeline.py", line 259, in <module>
    fire.Fire(main)
  File "/hdd2/kaylee/anaconda3/envs/AutoWS-Bench-101/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/hdd2/kaylee/anaconda3/envs/AutoWS-Bench-101/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/hdd2/kaylee/anaconda3/envs/AutoWS-Bench-101/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "fwrench/applications/pipeline.py", line 137, in main
    train_data_embed = embedder.transform(train_data)
  File "/hdd2/kaylee/AutoWS-Bench-101/fwrench/embeddings/openai_clip_embedding.py", line 79, in transform
    y = classes_[self.dataset]
KeyError: 'youtube'
